### PR TITLE
#1 Basic photo content type.

### PR DESCRIPTION
**Pull request by mrdavidburns**
Do I keep changes in `active` or move them into `staging`?

### CODE REVIEW

**Comment by sirkitree** [comment]
According to the README you should copy these files to prod-staging, then after you copy the file, commit it in git, push, pull on the other environment, then visit Configuration > Development > Configuration Management > Synchronize

**Comment by sirkitree** [comment]
`config/dev-*` folders and files should not be committed to the repo. Those stay on your local.

`config/prod-*` folders and files are in the repo and changes to those will go to production.

**Comment by sirkitree** [comment]
When I tried to sync these on my local (manually copied these files to dev-staging and went to sync in the ui) I got an error message: 
error 2016-02-29 08-32-54

Do I have something configured incorrectly? that directory name is accurate. I created symlinks instead of hard links - would that be it perhaps?]
cc @wesruv

**Comment by wesruv** [comment]
You know what... we should probably `.git-ignore` dev active, and when we have a change copy it to dev-staging and prod-staging. Hopefully that'd help us stay in sync.

@sirkitree 
Do you have a symlink from:
`REPO-ROOT/docroot/files/config_c72077* -> REPO-ROOT/config/dev-active`?

TBH this is the first time I've tried to setup a backdrop site with multiple devs, so it's likely things could be done better.

**Comment by wesruv** [comment]
I'll try to test this config later tonight.

**Comment by wesruv** [comment]
Yeah.... my site is a 500 error now.

Trying to sort out what's going on. Seems to be something with admin-menu...

**Comment by sirkitree** [comment]
This content type is now up on vr.lulladev.com

**Pull request closed without merging**
